# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # MODIFIED STEP
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Pipe the filtered requirements directly into pip
        grep -v '# dev' requirements.txt | pip install -r -

    - name: Test with pytest
      run: |
        pytest