# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 1) Drop lines that start with #
        # 2) Strip inline comments
        # 3) Install what's left
        grep -v '^\s*#' requirements.txt \
          | sed 's/#.*//' \
          | xargs pip install

          
    - name: Test with pytest
      run: |
        pytest